var user = {
login: "NicerHugs",
id: 8377050,
avatar_url: "https://avatars.githubusercontent.com/u/8377050?v=2",
gravatar_id: "8ef41b6a731187ad473ab50d10526470",
url: "https://api.github.com/users/NicerHugs",
html_url: "https://github.com/NicerHugs",
followers_url: "https://api.github.com/users/NicerHugs/followers",
following_url: "https://api.github.com/users/NicerHugs/following{/other_user}",
gists_url: "https://api.github.com/users/NicerHugs/gists{/gist_id}",
starred_url: "https://api.github.com/users/NicerHugs/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/NicerHugs/subscriptions",
organizations_url: "https://api.github.com/users/NicerHugs/orgs",
repos_url: "https://api.github.com/users/NicerHugs/repos",
events_url: "https://api.github.com/users/NicerHugs/events{/privacy}",
received_events_url: "https://api.github.com/users/NicerHugs/received_events",
type: "User",
site_admin: false,
name: "Jess Scheuring",
company: "",
blog: "",
location: "United States",
email: "nicerhugs@gmail.com",
hireable: false,
bio: null,
public_repos: 8,
public_gists: 0,
followers: 1,
following: 0,
created_at: "2014-08-06T17:51:09Z",
updated_at: "2014-09-10T03:57:47Z"
};
